import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/*
 *  Klasa Opcje
 *
 *  Klasa pozwala na zmiane hasla, adresu i nazwiska dla zalogowanego konta.
 *  Pozwala usunac konto i sprawdzic historie wypozyczen dla konta.
 *  Wyswietla nazwe, nazwisko i adres konta oraz liste filmow (po 5 na kazdej stronie).
 *  Pozwala na przemieszczanie sie po stronach z filmami oraz wyswietla ilosc pozostalych filmow.
 *  Pozwala takze na wylogowanie sie z konta czyli powrot do menu klienta.
 *
 *  Autor: Adam Filipowicz
 *  Data: 07 stycznia 2018 r.
 */
public class Opcje extends javax.swing.JFrame {
    protected static MenuKlient klientMenu;
    protected static WypozyczFilm wypozycz;
    private String nazwaKonta;
    private int numerStrony;
    protected Wypozyczalnia wypozyczalnia;
    protected static JOptionUserDialog UI = new JOptionUserDialog();
    private boolean wyszukane;
    private int iterator;
    private int iteratorPierwszego;
    private int iteratorOstatniego;
    
    private Opcje(){}
    
    public Opcje(String nazwaKonta, Wypozyczalnia wypozyczalnia) throws SQLException {
        initComponents();
        this.nazwaKonta = nazwaKonta;
        this.wypozyczalnia = wypozyczalnia;
        wyszukane = false;
        iterator = 0;
        iteratorPierwszego = 1;
        iteratorOstatniego = 1;
        String nazwisko = wypozyczalnia.getNazwisko(nazwaKonta);
        String adres = wypozyczalnia.getAdres(nazwaKonta);
        String imie = wypozyczalnia.getImie(nazwaKonta);
        nazwaText.setText("Nazwa konta: " + nazwaKonta);
        imieText.setText("Imię: " + imie);
        nazwiskoText.setText("Nazwisko: " + nazwisko);
        adresText.setText("Adres: " + adres);
        numerStrony=1;
        poprzedniaStronaButton.setEnabled(numerStrony!=1);
        nastepnaStronaButton.setEnabled(film5Button.getText()!=null);
        aktualizujFilmy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        zmienHasloButton = new javax.swing.JButton();
        zmienAdresButton = new javax.swing.JButton();
        zmienNazwiskoButton = new javax.swing.JButton();
        usunKontoButton = new javax.swing.JButton();
        przejrzyjHistorieButton = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        film1Button = new javax.swing.JButton();
        film2Button = new javax.swing.JButton();
        film3Button = new javax.swing.JButton();
        film4Button = new javax.swing.JButton();
        film5Button = new javax.swing.JButton();
        poprzedniaStronaButton = new javax.swing.JButton();
        nastepnaStronaButton = new javax.swing.JButton();
        wylogujButton = new javax.swing.JButton();
        numerStronyText = new javax.swing.JTextField();
        nazwiskoText = new javax.swing.JTextField();
        adresText = new javax.swing.JTextField();
        nazwaText = new javax.swing.JTextField();
        imieText = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        rokText = new javax.swing.JTextField();
        nazwaText2 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        wyszukajButton = new javax.swing.JButton();
        typText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        zmienHasloButton.setText("Zmien haslo");
        zmienHasloButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmienHasloButtonActionPerformed(evt);
            }
        });

        zmienAdresButton.setText("Zmien adres");
        zmienAdresButton.setToolTipText("");
        zmienAdresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmienAdresButtonActionPerformed(evt);
            }
        });

        zmienNazwiskoButton.setText("Zmien nazwisko");
        zmienNazwiskoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zmienNazwiskoButtonActionPerformed(evt);
            }
        });

        usunKontoButton.setText("Usun konto");
        usunKontoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usunKontoButtonActionPerformed(evt);
            }
        });

        przejrzyjHistorieButton.setText("Przejrzyj historie wypozyczen");
        przejrzyjHistorieButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przejrzyjHistorieButtonActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Opcje konta");

        jTextField2.setEditable(false);
        jTextField2.setText("Zalogowano na konto:");

        jTextField3.setEditable(false);
        jTextField3.setText("Lista filmów:");

        film1Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film1ButtonActionPerformed(evt);
            }
        });

        film2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film2ButtonActionPerformed(evt);
            }
        });

        film3Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film3ButtonActionPerformed(evt);
            }
        });

        film4Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film4ButtonActionPerformed(evt);
            }
        });

        film5Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                film5ButtonActionPerformed(evt);
            }
        });

        poprzedniaStronaButton.setText("Poprzednia strona");
        poprzedniaStronaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poprzedniaStronaButtonActionPerformed(evt);
            }
        });

        nastepnaStronaButton.setText("Nastepna strona");
        nastepnaStronaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastepnaStronaButtonActionPerformed(evt);
            }
        });

        wylogujButton.setText("Wyloguj");
        wylogujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wylogujButtonActionPerformed(evt);
            }
        });

        numerStronyText.setEditable(false);
        numerStronyText.setText("Strona: ");

        nazwiskoText.setEditable(false);
        nazwiskoText.setText("Nazwisko: ");

        adresText.setEditable(false);
        adresText.setText("Adres:");

        nazwaText.setEditable(false);
        nazwaText.setText("Nazwa konta:");

        imieText.setEditable(false);
        imieText.setText("Imię:");

        jTextField4.setEditable(false);
        jTextField4.setText("Wyszukiwarka filmów:");

        jTextField9.setEditable(false);
        jTextField9.setText("Typ filmu:");

        jTextField17.setEditable(false);
        jTextField17.setText("Rok powstania:");

        jTextField10.setEditable(false);
        jTextField10.setText("Nazwa filmu:");

        wyszukajButton.setText("Wyszukaj");
        wyszukajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyszukajButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(nazwiskoText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                .addComponent(imieText, javax.swing.GroupLayout.Alignment.LEADING)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(nazwaText2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(wylogujButton)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(rokText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(typText, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(adresText)
                        .addGap(134, 134, 134)
                        .addComponent(wyszukajButton)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(przejrzyjHistorieButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zmienHasloButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zmienAdresButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usunKontoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(zmienNazwiskoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(210, 210, 210)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(168, 168, 168))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(film4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(film5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(film1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(film3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(film2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(121, 121, 121))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(poprzedniaStronaButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(nastepnaStronaButton)
                                        .addGap(73, 73, 73))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(numerStronyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(195, 195, 195))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(wylogujButton)
                        .addGap(13, 13, 13)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nazwaText2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(typText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(imieText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rokText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nazwiskoText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(wyszukajButton, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(adresText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(zmienHasloButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zmienAdresButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zmienNazwiskoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usunKontoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(film1Button, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(film2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(film3Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(film4Button, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(film5Button, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(przejrzyjHistorieButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(numerStronyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(poprzedniaStronaButton)
                            .addComponent(nastepnaStronaButton)))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda po nacisnieciu guzika wylogowuje sie i wraca do menu klienta.
     * @param evt - nacisniecie guzika powoduje wylogowanie sie i powrot do menu klienta
     */
    private void wylogujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wylogujButtonActionPerformed
        klientMenu = new MenuKlient(wypozyczalnia);
        klientMenu.setResizable(false);
        klientMenu.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        klientMenu.setSize(800,500);
        klientMenu.setLocation(500,250);
        klientMenu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wylogujButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na zmiane hasla.
     * @param evt - nacisniecie guzika powoduje zmiane hasla
     */
    private void zmienHasloButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmienHasloButtonActionPerformed
        String noweHaslo;
        String stareHaslo;

        stareHaslo = UI.enterHashString("Podaj stare haslo: ");
        noweHaslo = UI.enterHashString("Podaj nowe haslo: ");
        if (noweHaslo.equals("")){
            UI.printErrorMessage("Haslo nie moze byc puste");
            return;
        }
        try {
            if(wypozyczalnia.sprawdzHaslo(stareHaslo, nazwaKonta)){
                wypozyczalnia.setHaslo(stareHaslo, noweHaslo, nazwaKonta);
                UI.printInfoMessage("\nHaslo zostalo zmienione");
                return;
            }
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        UI.printErrorMessage("Podano bledne stare haslo!");
    }//GEN-LAST:event_zmienHasloButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na zmiane adresu.
     * @param evt - nacisniecie guzika powoduje zmiane adresu
     */
    private void zmienAdresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmienAdresButtonActionPerformed
        String noweWojewodztwo, noweMiasto, nowaUlica; 
        int nowyNr1, nowyNr2;

        UI.printMessage("\nZMIANA ADRESU WLASCICIELA KONTA");
        noweWojewodztwo = UI.enterString("Podaj wojewodztwo: ");
        noweMiasto = UI.enterString("Podaj miasto: ");
        nowaUlica = UI.enterString("Podaj ulicę: ");
        nowyNr1 = UI.enterInt("Podaj numer domu: ");
        nowyNr2 = UI.enterInt("Podaj numer mieszkania: ");
        try {
            wypozyczalnia.setAdres(noweWojewodztwo, noweMiasto, nowaUlica, nowyNr1, nowyNr2, nazwaKonta);
            adresText.setText("Adres: "+wypozyczalnia.getAdres(nazwaKonta));
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        UI.printInfoMessage("\nAdres zostal zmieniony");
    }//GEN-LAST:event_zmienAdresButtonActionPerformed

    /**nazwaKonta
     * Metoda po nacisnieciu guzika pozwala na zmiane nazwiska.
     * @param evt - nacisniecie guzika powoduje zmiane nazwiska
     */
    private void zmienNazwiskoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zmienNazwiskoButtonActionPerformed
        String noweNazwisko;

        UI.printMessage("\nZMIANA NAZWISKA WLASCICIELA KONTA");
        noweNazwisko = UI.enterString("Podaj nazwisko: ");
        if (noweNazwisko.equals("")){
            UI.printErrorMessage("Nazwisko nie moze byc puste");
            return;
        }
        try {
            wypozyczalnia.setNazwisko(noweNazwisko, nazwaKonta);
            nazwiskoText.setText("Nazwisko: "+wypozyczalnia.getNazwisko(nazwaKonta));
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        UI.printInfoMessage("\nNazwisko zostalo zmienione");
    }//GEN-LAST:event_zmienNazwiskoButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na usuniecie konta.
     * @param evt - nacisniecie guzika powoduje usuniecie konta
     */
    private void usunKontoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usunKontoButtonActionPerformed
        String odpowiedz;
        String haslo;
        UI.printMessage("\nUSUWANIE KONTA");
        haslo = UI.enterString("Podaj haslo: ");
        try {
            if(wypozyczalnia.sprawdzHaslo(haslo, nazwaKonta)){
                odpowiedz = UI.enterString("Czy na pewno usunac to konto? (TAK/NIE)");
                if (!odpowiedz.equals("TAK")) {
                    UI.printErrorMessage("\nKonto nie zostalo usuniete");
                    return;
                }
                wypozyczalnia.usunKonto(nazwaKonta);
                UI.printInfoMessage("\nKonto zostalo usuniete");
                klientMenu.setVisible(true);
                this.setVisible(false);
                return;
            }
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        UI.printErrorMessage("Podano bledne haslo!");
    }//GEN-LAST:event_usunKontoButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na wyswietlenie historii zakupow.
     * @param evt - nacisniecie guzika powoduje wyswietlenie historii zakupow
     */
    private void przejrzyjHistorieButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przejrzyjHistorieButtonActionPerformed
        UI.printMessage("\nHISTORIA ZAKUPOW");
        try {
            UI.printInfoMessage(wypozyczalnia.wyswietlHistorieWypozyczenKlienta(nazwaKonta));
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_przejrzyjHistorieButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na zmiane strony na poprzednia (minimalnie 1).
     * @param evt - nacisniecie guzika powoduje zmiane strony
     */
    private void poprzedniaStronaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poprzedniaStronaButtonActionPerformed
        if(numerStrony>1){
            numerStrony--;
            try {
                if(wyszukane)
                    aktualizujFilmyWyszukaneOdTylu();
                else
                    aktualizujFilmyOdTylu();
            } catch (Exception ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
        poprzedniaStronaButton.setEnabled(numerStrony!=1);
        nastepnaStronaButton.setEnabled(film5Button.getText()!=null);
    }//GEN-LAST:event_poprzedniaStronaButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika pozwala na zmiane strony na nastepna.
     * @param evt - nacisniecie guzika powoduje zmiane strony
     */
    private void nastepnaStronaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastepnaStronaButtonActionPerformed
        if(film5Button.getText()!=null){
            numerStrony++;
            try {
                if(wyszukane)
                    aktualizujFilmyWyszukane();
                else
                    aktualizujFilmy();
            } catch (Exception ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
        poprzedniaStronaButton.setEnabled(numerStrony!=1);
        nastepnaStronaButton.setEnabled(film5Button.getText()!=null);
    }//GEN-LAST:event_nastepnaStronaButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika przechodzi do wypozyczenia podanego filmu.
     * @param evt - nacisniecie guzika powoduje przejscie do wypozyczenia filmu
     */
    private void film1ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_film1ButtonActionPerformed
        if(film1Button.getText()==null){
            return;
        }
        try {
            if(wypozyczalnia.znajdzFilm(film1Button.getText())){
                wypozycz = new WypozyczFilm(nazwaKonta,film1Button.getText(),wypozyczalnia);
                wypozycz.setResizable(false);
                wypozycz.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                wypozycz.setSize(800,500);
                wypozycz.setLocation(500,250);
                wypozycz.setVisible(true);
                this.dispose();
            }
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_film1ButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika przechodzi do wypozyczenia podanego filmu.
     * @param evt - nacisniecie guzika powoduje przejscie do wypozyczenia filmu
     */
    private void film2ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_film2ButtonActionPerformed
        if(film2Button.getText()==null){
            return;
        }
        try {
            if(wypozyczalnia.znajdzFilm(film2Button.getText())){
                wypozycz = new WypozyczFilm(nazwaKonta,film2Button.getText(),wypozyczalnia);
                wypozycz.setResizable(false);
                wypozycz.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                wypozycz.setSize(800,500);
                wypozycz.setLocation(500,250);
                wypozycz.setVisible(true);
                this.dispose();
            }
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_film2ButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika przechodzi do wypozyczenia podanego filmu.
     * @param evt - nacisniecie guzika powoduje przejscie do wypozyczenia filmu
     */
    private void film3ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_film3ButtonActionPerformed
        if(film3Button.getText()==null){
            return;
        }
        try {
            if(wypozyczalnia.znajdzFilm(film3Button.getText())){
                wypozycz = new WypozyczFilm(nazwaKonta,film3Button.getText(),wypozyczalnia);
                wypozycz.setResizable(false);
                wypozycz.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                wypozycz.setSize(800,500);
                wypozycz.setLocation(500,250);
                wypozycz.setVisible(true);
                this.dispose();
            }
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_film3ButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika przechodzi do wypozyczenia podanego filmu.
     * @param evt - nacisniecie guzika powoduje przejscie do wypozyczenia filmu
     */
    private void film4ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_film4ButtonActionPerformed
        if(film4Button.getText()==null){
            return;
        }
        try {
            if(wypozyczalnia.znajdzFilm(film4Button.getText())){
                wypozycz = new WypozyczFilm(nazwaKonta,film4Button.getText(),wypozyczalnia);
                wypozycz.setResizable(false);
                wypozycz.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                wypozycz.setSize(800,500);
                wypozycz.setLocation(500,250);
                wypozycz.setVisible(true);
                this.dispose();
            }
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_film4ButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika przechodzi do wypozyczenia podanego filmu.
     * @param evt - nacisniecie guzika powoduje przejscie do wypozyczenia filmu
     */
    private void film5ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_film5ButtonActionPerformed
        if(film5Button.getText()==null){
            return;
        }
        try {
            if(wypozyczalnia.znajdzFilm(film5Button.getText())){
                wypozycz = new WypozyczFilm(nazwaKonta,film5Button.getText(),wypozyczalnia);
                wypozycz.setResizable(false);
                wypozycz.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
                wypozycz.setSize(800,500);
                wypozycz.setLocation(500,250);
                wypozycz.setVisible(true);
                this.dispose();
            }
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
    }//GEN-LAST:event_film5ButtonActionPerformed

    private void wyszukajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyszukajButtonActionPerformed
        numerStrony = 1;
        iterator = 0;
        iteratorPierwszego = 1;
        iteratorOstatniego = 1;
        
        if(nazwaText2.getText().equals("") && typText.getText().equals("") && rokText.getText().equals("")){
            wyszukane=false;
            try {
                aktualizujFilmy();
            } catch (SQLException ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
        else{
            wyszukane=true;
            try {
                aktualizujFilmyWyszukane();
            } catch (SQLException ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
        poprzedniaStronaButton.setEnabled(numerStrony!=1);
        nastepnaStronaButton.setEnabled(film5Button.getText()!=null);
    }//GEN-LAST:event_wyszukajButtonActionPerformed

    
    /**
     * Metoda aktualizuje numer strony, nazwy filmow na guzikach oraz znaczniki czy film jest dostepny czy nie.
     * Metoda wywolywana przy inicjalizacji klasy oraz przy zmianie strony filmow.
     */
    public void aktualizujFilmy() throws SQLException{
        iterator++;
        iteratorPierwszego = iterator;
        numerStronyText.setText("Strona: "+numerStrony);
        do{
            film1Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator++;
        } while(film1Button.getText()!=null && film1Button.getText().equals("XWX"));
        do{
            film2Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator++;
        } while(film2Button.getText()!=null && film2Button.getText().equals("XWX"));
        do{
            film3Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator++;
        } while(film3Button.getText()!=null && film3Button.getText().equals("XWX"));
        do{
            film4Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator++;
        } while(film4Button.getText()!=null && film4Button.getText().equals("XWX"));
        do{
            film5Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator++;
        } while(film5Button.getText()!=null && film5Button.getText().equals("XWX"));
        iterator--;
        iteratorOstatniego = iterator;
    }
    
    /**
     * Metoda aktualizuje numer strony, nazwy filmow na guzikach oraz znaczniki czy film jest dostepny czy nie.
     * Metoda wywolywana przy inicjalizacji klasy oraz przy zmianie strony filmow.
     */
    public void aktualizujFilmyWyszukane() throws SQLException{
        iterator++;
        iteratorPierwszego = iterator;
        numerStronyText.setText("Strona: "+numerStrony);
        int rokkText;
        if(rokText.getText().equals("")){
            rokkText=0;
        }
        else{
            rokkText = Integer.parseInt(rokText.getText());
        }
        do{
            film1Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator++;
        } while(film1Button.getText()!=null && film1Button.getText().equals("XWX"));
        do{
            film2Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator++;
        } while(film2Button.getText()!=null && film2Button.getText().equals("XWX"));
        do{
            film3Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator++;
        } while(film3Button.getText()!=null && film3Button.getText().equals("XWX"));
        do{
            film4Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator++;
        } while(film4Button.getText()!=null && film4Button.getText().equals("XWX"));
        do{
            film5Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator++;
        } while(film5Button.getText()!=null && film5Button.getText().equals("XWX"));
        iterator--;
        iteratorOstatniego = iterator;
    }
    
    /**
     * Metoda aktualizuje numer strony, nazwy filmow na guzikach oraz znaczniki czy film jest dostepny czy nie.
     * Metoda wywolywana przy inicjalizacji klasy oraz przy zmianie strony filmow.
     */
    public void aktualizujFilmyOdTylu() throws SQLException{
        iterator = iteratorPierwszego - 1;
        iteratorOstatniego = iterator;
        numerStronyText.setText("Strona: "+numerStrony);
        do{
            film5Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator--;
        } while(film5Button.getText()!=null && film5Button.getText().equals("XWX"));
        do{
            film4Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator--;
        } while(film4Button.getText()!=null && film4Button.getText().equals("XWX"));
        do{
            film3Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator--;
        } while(film3Button.getText()!=null && film3Button.getText().equals("XWX"));
        do{
            film2Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator--;
        } while(film2Button.getText()!=null && film2Button.getText().equals("XWX"));
        do{
            film1Button.setText(wypozyczalnia.znajdzNazweFilmu(iterator));
            iterator--;
        } while(film1Button.getText()!=null && film1Button.getText().equals("XWX"));
        iterator++;
        iteratorPierwszego = iterator;
        iterator = iteratorOstatniego;
    }
    
    /**
     * Metoda aktualizuje numer strony, nazwy filmow na guzikach oraz znaczniki czy film jest dostepny czy nie.
     * Metoda wywolywana przy inicjalizacji klasy oraz przy zmianie strony filmow.
     */
    public void aktualizujFilmyWyszukaneOdTylu() throws SQLException{
        iterator = iteratorPierwszego - 1;
        iteratorOstatniego = iterator;
        numerStronyText.setText("Strona: "+numerStrony);
        int rokkText;
        if(rokText.getText().equals("")){
            rokkText=0;
        }
        else{
            rokkText = Integer.parseInt(rokText.getText());
        }
        do{
            film5Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator--;
        } while(film5Button.getText()!=null && film5Button.getText().equals("XWX"));
        do{
            film4Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator--;
        } while(film4Button.getText()!=null && film4Button.getText().equals("XWX"));
        do{
            film3Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator--;
        } while(film3Button.getText()!=null && film3Button.getText().equals("XWX"));
        do{
            film2Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator--;
        } while(film2Button.getText()!=null && film2Button.getText().equals("XWX"));
        do{
            film1Button.setText(wypozyczalnia.znajdzFilmy(nazwaText2.getText(), typText.getText(), rokkText,iterator));
            iterator--;
        } while(film1Button.getText()!=null && film1Button.getText().equals("XWX"));
        iterator++;
        iteratorPierwszego = iterator;
        iterator = iteratorOstatniego;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Opcje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Opcje().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adresText;
    private javax.swing.JButton film1Button;
    private javax.swing.JButton film2Button;
    private javax.swing.JButton film3Button;
    private javax.swing.JButton film4Button;
    private javax.swing.JButton film5Button;
    private javax.swing.JTextField imieText;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton nastepnaStronaButton;
    private javax.swing.JTextField nazwaText;
    private javax.swing.JTextField nazwaText2;
    private javax.swing.JTextField nazwiskoText;
    private javax.swing.JTextField numerStronyText;
    private javax.swing.JButton poprzedniaStronaButton;
    private javax.swing.JButton przejrzyjHistorieButton;
    private javax.swing.JTextField rokText;
    private javax.swing.JTextField typText;
    private javax.swing.JButton usunKontoButton;
    private javax.swing.JButton wylogujButton;
    private javax.swing.JButton wyszukajButton;
    private javax.swing.JButton zmienAdresButton;
    private javax.swing.JButton zmienHasloButton;
    private javax.swing.JButton zmienNazwiskoButton;
    // End of variables declaration//GEN-END:variables
}
