import java.sql.SQLException;
import javax.swing.JFrame;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 *  Klasa Platnosc
 *
 *  Klasa pozwala na wybranie przelewu bankowego i przekierowanie do platnosci bankowej,
 *  a nastepnie wypozyczenie wybranego filmu i powrot do opcji klienta,
 *  oraz anulowanie wypozyczenia (powrot do opcji klienta).
 *
 *  Autor: Adam Filipowicz
 *  Data: 31 maja 2017 r.
 */
public class Platnosc extends javax.swing.JFrame {
    protected static WypozyczFilm wypozycz;
    protected static Opcje opcje;
    protected static String nazwa;
    private String nazwaKonta;
    protected Wypozyczalnia wypozyczalnia;
    protected static JOptionUserDialog UI = new JOptionUserDialog();
    
    private Platnosc(){}
    
    public Platnosc(String nazwaKonta, String nazwa, Wypozyczalnia wypozyczalnia){
        initComponents();
        this.nazwaKonta = nazwaKonta;
        this.nazwa=nazwa;
        this.wypozyczalnia = wypozyczalnia;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        przelewButton = new javax.swing.JButton();
        anulujButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Wybierz sposob platnosci");

        przelewButton.setText("Przelew bankowy");
        przelewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                przelewButtonActionPerformed(evt);
            }
        });

        anulujButton.setText("Anuluj wypozyczenie");
        anulujButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anulujButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(323, 323, 323)
                        .addComponent(przelewButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(anulujButton)))
                .addContainerGap(246, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(przelewButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 297, Short.MAX_VALUE)
                .addComponent(anulujButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Metoda po nacisnieciu guzika przechodzi do platnosci bankowej oraz wypozycza wybrany film.
     * @param evt - nacisniecie guzika powoduje przejscie do platnosci bankowej oraz wypozyczenie filmu
     */
    private void przelewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_przelewButtonActionPerformed
        UI.printInfoMessage("\nPrzekierowanie na przelew bankowy");
        Calendar today = Calendar.getInstance();
        today.set(Calendar.HOUR_OF_DAY, 0);
        today.set(Calendar.MINUTE, 0);
        today.set(Calendar.SECOND, 0);
        int naprawMiesiac = today.get(Calendar.MONTH)+1;
        int naprawDzien = today.get(Calendar.DAY_OF_MONTH);
        String miesiac;
        String dzien;
        if(naprawMiesiac<10)
            miesiac="0"+Integer.toString(naprawMiesiac);
        else
            miesiac=Integer.toString(naprawMiesiac);
        if(naprawDzien<10)
            dzien="0"+Integer.toString(naprawDzien);
        else
            dzien=Integer.toString(naprawDzien);
        String dataWypozyczenia = today.get(Calendar.YEAR)+"-"+miesiac+"-"+dzien; //dzisiejsza data
        today.add(Calendar.DAY_OF_MONTH, 7);
        naprawMiesiac=today.get(Calendar.MONTH)+1;
        naprawDzien = today.get(Calendar.DAY_OF_MONTH);
        if(naprawMiesiac<10)
            miesiac="0"+Integer.toString(naprawMiesiac);
        else
            miesiac=Integer.toString(naprawMiesiac);
        if(naprawDzien<10)
            dzien="0"+Integer.toString(naprawDzien);
        else
            dzien=Integer.toString(naprawDzien);
        String dataZwrotu = today.get(Calendar.YEAR)+"-"+miesiac+"-"+dzien; //data za tydzien
        try {
            wypozyczalnia.dodajDoHistoriiWypozyczen(nazwa, wypozyczalnia.getCena(nazwa), nazwaKonta, dataWypozyczenia, dataZwrotu);
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        UI.printInfoMessage("\nWypozyczyles "+nazwa);
        
        try {
            opcje = new Opcje(nazwaKonta, wypozyczalnia);
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        opcje.setResizable(false);
        opcje.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        opcje.setSize(800,500);
        opcje.setLocation(500,250);
        opcje.setVisible(true);
        try {
            opcje.aktualizujFilmy();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        this.dispose();
    }//GEN-LAST:event_przelewButtonActionPerformed

    /**
     * Metoda po nacisnieciu guzika wraca do opcji klienta.
     * @param evt - nacisniecie guzika powoduje powrot do opcji klienta
     */
    private void anulujButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anulujButtonActionPerformed
        try {
            opcje = new Opcje(nazwaKonta, wypozyczalnia);
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        opcje.setResizable(false);
        opcje.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        opcje.setSize(800,500);
        opcje.setLocation(500,250);
        opcje.setVisible(true);
        try {
            opcje.aktualizujFilmy();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        this.dispose();
    }//GEN-LAST:event_anulujButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Platnosc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Platnosc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anulujButton;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton przelewButton;
    // End of variables declaration//GEN-END:variables
}
