import java.sql.SQLException;
import javax.swing.JFrame;

/*
 *  Klasa Wypozyczenia
 *
 *  Klasa pozwala na przejrzenie wypozyczen, zwrocenie wybranych wypozyczen,
 *  oraz przejrzenie wypozyczen wybranego klienta.
 *
 *  Autor: Adam Filipowicz
 *  Data: 07 stycznia 2018 r.
 */
public class Wypozyczenia extends javax.swing.JFrame {
    private String nazwaKonta;
    private Wypozyczenie wyp;
    protected static OpcjeS opcje;
    private int numerWypozyczenia;
    protected Wypozyczalnia wypozyczalnia;
    protected static JOptionUserDialog UI = new JOptionUserDialog();
    private boolean wyszukane;
    
    private Wypozyczenia() {}
    
    public Wypozyczenia(String nazwaKonta, Wypozyczalnia wypozyczalnia) throws SQLException{
        initComponents();
        this.nazwaKonta = nazwaKonta;
        this.wypozyczalnia = wypozyczalnia;
        numerWypozyczenia = 1;
        wyszukane = false;
        poprzednieWypButton.setEnabled(numerWypozyczenia!=1);
        nastepneWypButton.setEnabled(!IDText.getText().equals("ID wypozyczenia: 1"));
        aktualizujWypozyczenie();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        IDText1 = new javax.swing.JTextField();
        poprzednieWypButton = new javax.swing.JButton();
        nastepneWypButton = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();
        nazwaText1 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        nazwaKlientaText1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        wyszukajButton = new javax.swing.JButton();
        wrocSButton = new javax.swing.JButton();
        cenaText = new javax.swing.JTextField();
        nazwaText = new javax.swing.JTextField();
        nazwaKlientaText = new javax.swing.JTextField();
        IDText = new javax.swing.JTextField();
        dataZakText = new javax.swing.JTextField();
        dataWypText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setText("Przejrzyj wypożyczenia");

        jTextField5.setEditable(false);
        jTextField5.setText("Nazwa klienta");

        poprzednieWypButton.setText("Poprzednie wypożyczenie");
        poprzednieWypButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poprzednieWypButtonActionPerformed(evt);
            }
        });

        nastepneWypButton.setText("Nastepne wypożyczenie");
        nastepneWypButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nastepneWypButtonActionPerformed(evt);
            }
        });

        jTextField9.setEditable(false);
        jTextField9.setText("ID wypozyczenia");

        jTextField10.setEditable(false);
        jTextField10.setText("Nazwa filmu");

        jTextField4.setEditable(false);
        jTextField4.setText("Wyszukiwarka wypożyczeń:");

        wyszukajButton.setText("Wyszukaj");
        wyszukajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wyszukajButtonActionPerformed(evt);
            }
        });

        wrocSButton.setText("Wroc do menu glownego");
        wrocSButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wrocSButtonActionPerformed(evt);
            }
        });

        cenaText.setEditable(false);
        cenaText.setText("Cena wypozyczenia:");

        nazwaText.setEditable(false);
        nazwaText.setText("Nazwa filmu:");

        nazwaKlientaText.setEditable(false);
        nazwaKlientaText.setText("Nazwa klienta:");

        IDText.setEditable(false);
        IDText.setText("ID wypozyczenia:");

        dataZakText.setEditable(false);
        dataZakText.setText("Data zakończenia:");

        dataWypText.setEditable(false);
        dataWypText.setText("Data wypożyczenia:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(254, 254, 254))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nastepneWypButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(poprzednieWypButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dataWypText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazwaKlientaText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataZakText, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(IDText, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                                .addComponent(nazwaText)))
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IDText1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nazwaText1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(nazwaKlientaText1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(wyszukajButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(43, 43, 43)))))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(wrocSButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(IDText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nazwaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(nazwaKlientaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cenaText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataWypText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dataZakText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazwaText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nazwaKlientaText1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wyszukajButton)))
                .addGap(12, 12, 12)
                .addComponent(poprzednieWypButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nastepneWypButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(wrocSButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void poprzednieWypButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poprzednieWypButtonActionPerformed
        if(numerWypozyczenia>1){
            numerWypozyczenia--;
            try {
                if(wyszukane)
                    aktualizujWypozyczenieWyszukane();
                else
                    aktualizujWypozyczenie();
            } catch (Exception ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
        poprzednieWypButton.setEnabled(numerWypozyczenia!=1);
    }//GEN-LAST:event_poprzednieWypButtonActionPerformed
        
    private void nastepneWypButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nastepneWypButtonActionPerformed
        numerWypozyczenia++;
        try {
            if(wyszukane)
                aktualizujWypozyczenieWyszukane();
            else
                aktualizujWypozyczenie();
        } catch (Exception ex) {
            UI.printErrorMessage(ex.getMessage());
            return;
        }
        poprzednieWypButton.setEnabled(numerWypozyczenia!=1);
    }//GEN-LAST:event_nastepneWypButtonActionPerformed

    private void wyszukajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wyszukajButtonActionPerformed
        numerWypozyczenia=1;
        if(nazwaText1.getText().equals("") && nazwaKlientaText1.getText().equals("") && IDText1.getText().equals("")){
            wyszukane=false;
            try {
                aktualizujWypozyczenie();
            } catch (SQLException ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
        else{
            wyszukane=true;
            try {
                aktualizujWypozyczenieWyszukane();
            } catch (SQLException ex) {
                UI.printErrorMessage(ex.getMessage());
                return;
            }
        }
        poprzednieWypButton.setEnabled(numerWypozyczenia!=1);
        nastepneWypButton.setEnabled(!IDText.getText().equals("ID wypozyczenia: 1"));
    }//GEN-LAST:event_wyszukajButtonActionPerformed

    private void wrocSButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wrocSButtonActionPerformed
        try {
            opcje = new OpcjeS(nazwaKonta, wypozyczalnia);
        } catch (Exception e) {
            UI.printErrorMessage(e.getMessage());
            return;
        }
        opcje.setResizable(false);
        opcje.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        opcje.setSize(800,500);
        opcje.setLocation(500,250);
        opcje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_wrocSButtonActionPerformed

    public void aktualizujWypozyczenie() throws SQLException{
        wyp = wypozyczalnia.znajdzWypozyczenieCale(numerWypozyczenia);
        if(wyp==null){
            numerWypozyczenia--;
            nastepneWypButton.setEnabled(false);
            return;
        }
        nastepneWypButton.setEnabled(true);
        IDText.setText("ID wypozyczenia: "+Integer.toString(wyp.getID()));
        nazwaKlientaText.setText("Nazwa klienta: "+wyp.getNazwaKlienta());
        nazwaText.setText("Nazwa filmu: "+wyp.getNazwaFilmu());
        dataWypText.setText("Data wypozyczenia: "+wyp.getDataWypozyczenia());
        dataZakText.setText("Data zakończenia: "+wyp.getDataZwrotu());
        cenaText.setText("Cena wypożyczenia: "+Double.toString(wyp.getCena()));
    }
    
    public void aktualizujWypozyczenieWyszukane() throws SQLException{
        int iddText;
        if(IDText1.getText().equals("")){
            iddText=0;
        }
        else{
            iddText = Integer.parseInt(IDText1.getText());
        }
        wyp = wypozyczalnia.znajdzWypozyczenieCaleWyszukane(iddText, nazwaText1.getText(), nazwaKlientaText1.getText(), numerWypozyczenia);
        if(wyp==null){
            numerWypozyczenia--;
            nastepneWypButton.setEnabled(false);
            return;
        }
        nastepneWypButton.setEnabled(true);
        IDText.setText("ID wypozyczenia: "+Integer.toString(wyp.getID()));
        nazwaKlientaText.setText("Nazwa klienta: "+wyp.getNazwaKlienta());
        nazwaText.setText("Nazwa filmu: "+wyp.getNazwaFilmu());
        dataWypText.setText("Data wypozyczenia: "+wyp.getDataWypozyczenia());
        dataZakText.setText("Data zakończenia: "+wyp.getDataZwrotu());
        cenaText.setText("Cena wypożyczenia: "+Double.toString(wyp.getCena()));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZmienFilmy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Wypozyczenia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDText;
    private javax.swing.JTextField IDText1;
    private javax.swing.JTextField cenaText;
    private javax.swing.JTextField dataWypText;
    private javax.swing.JTextField dataZakText;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JButton nastepneWypButton;
    private javax.swing.JTextField nazwaKlientaText;
    private javax.swing.JTextField nazwaKlientaText1;
    private javax.swing.JTextField nazwaText;
    private javax.swing.JTextField nazwaText1;
    private javax.swing.JButton poprzednieWypButton;
    private javax.swing.JButton wrocSButton;
    private javax.swing.JButton wyszukajButton;
    // End of variables declaration//GEN-END:variables
}
